name: Verify
on:
  workflow_call:
  workflow_dispatch:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Check code
        run: pnpm check

      - name: Check types
        run: pnpm check:types

  test:
    name: Test Runtime
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run tests
        run: pnpm run test --bail=1
        env:
          CI: true
